services:
  db:
    container_name: db
    image: postgres:16
    restart: "always"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${BACKEND_DB_NAME}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
      - POSTGRES_USER=${BACKEND_DB_USERNAME}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -d ${BACKEND_DB_NAME} -U ${BACKEND_DB_USERNAME}"]
      interval: 5s
      timeout: 10s
      retries: 10
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
  backend:
    container_name: backend
    build:
      context: ./go
      dockerfile: Dockerfile.multistage
    environment:
      DATABASE_USERNAME: ${BACKEND_DB_USERNAME}
      DATABASE_PASSWORD: ${BACKEND_DB_PASSWORD}
      DATABASE_HOST: db
      DATABASE_NAME: ${BACKEND_DB_NAME}
      BCRYPT_COST: ${BACKEND_BCRYPT_COST}
      JWT_SECRET: ${BACKEND_JWT_SECRET}
      JWT_ISSUER: ${BACKEND_JWT_ISSUER}
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: frontend
    build:
      context: ./sveltekit
      dockerfile: Dockerfile.multistage
    environment:
      DB_HOST: db
      DB_NAME: ${BACKEND_DB_NAME}
      DB_USERNAME: ${BACKEND_DB_USERNAME}
      DB_PASSWORD: ${BACKEND_DB_PASSWORD}
    depends_on:
      backend:
        condition: service_started
    tty: true
  nginx:
    container_name: nginx
    image: nginx:1.27.3-bookworm-perl
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./--logs/nginx:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      pgadmin:
        condition: service_started

volumes:
  postgres_data:
  pgadmin:
